# Generated by Django 4.1.5 on 2023-02-02 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
