# Generated by Django 4.1.5 on 2023-02-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file',
            field=models.FileField(default='', upload_to='app/static/upload/'),
        ),
    ]
