# Generated by Django 4.1.5 on 2023-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_application_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='file',
            field=models.ImageField(null=True, upload_to='app/static/upload'),
        ),
    ]
