# Generated by Django 4.1.5 on 2023-02-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobs_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(upload_to='app/static/upload/'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
