# Generated by Django 4.1.5 on 2023-02-03 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_application_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(upload_to='applicant/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
