# Generated by Django 4.1.5 on 2023-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_application_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='dp',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='file',
            field=models.ImageField(null=True, upload_to='users/dp/'),
        ),
    ]
