# Generated by Django 4.1.5 on 2023-02-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobseeker_dp_alter_jobs_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='dp',
            new_name='file',
        ),
    ]
