# Generated by Django 4.1.5 on 2023-02-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_dp_jobseeker_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='file',
        ),
    ]
