# Generated by Django 4.1.5 on 2023-02-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_jobseeker_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='file',
        ),
    ]
