# Generated by Django 4.1.5 on 2023-02-06 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_jobs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='form_end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
