# Generated by Django 4.1.5 on 2023-02-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_jobs_form_start_date_alter_jobs_form_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='form_end_date',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='form_start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
