# Generated by Django 4.1.5 on 2023-02-06 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_jobs_form_end_date_alter_jobs_form_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='form_start_date',
        ),
        migrations.AddField(
            model_name='jobs',
            name='form_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
