# Generated by Django 4.1.5 on 2023-02-06 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_jobs_form_start_date_jobs_form_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='form_end_date',
            new_name='application_end_date',
        ),
        migrations.AddField(
            model_name='jobs',
            name='application_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
