# Generated by Django 4.1.5 on 2023-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_form_end_date_jobs_application_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='application_end_date',
            field=models.DateField(null=True),
        ),
    ]
