# Generated by Django 4.1.5 on 2023-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_jobs_application_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='application_start_date',
            field=models.DateField(null=True),
        ),
    ]
