# Generated by Django 4.2 on 2023-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_jobs_application_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
