# Generated by Django 4.2 on 2023-05-01 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_jobseeker_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('about_you', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=1000)),
                ('career', models.CharField(max_length=1000)),
                ('job_1_start', models.DateField()),
                ('job_1_end', models.DateField()),
                ('job_1_details', models.CharField(max_length=1000)),
                ('job_2_start', models.DateField()),
                ('job_2_end', models.DateField()),
                ('job_2_details', models.CharField(max_length=1000)),
                ('job_3_start', models.DateField()),
                ('job_3_end', models.DateField()),
                ('job_3_details', models.CharField(max_length=1000)),
                ('references', models.CharField(max_length=1000)),
                ('jobseeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
