# Generated by Django 4.2 on 2023-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_you',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='career',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_1_details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_1_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_1_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='references',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
