# Generated by Django 4.2 on 2023-05-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_resume_about_you_alter_resume_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_2_details',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_2_end',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_2_start',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_3_details',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_3_end',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_3_start',
        ),
    ]
