# Generated by Django 4.2 on 2023-05-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_resume_job_2_details_remove_resume_job_2_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
