# Generated by Django 4.2 on 2023-05-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
